# Requires SDL shadercross

import os
import subprocess
import json

shadercross_path = "C:/shadercross/bin/shadercross.exe";
formats = ["spv", "msl", "dxil"]
shader_list = []

for (root, dirs, files) in os.walk("..\\shaders"):
    for file in files:
        full_path = os.path.abspath(os.path.join(root, file))

        if file.endswith("hlsl"):
            for format in formats:
                path = f"../assets/shaders/{format}"
                if not os.path.exists(path): os.makedirs(path)
                subprocess.run([shadercross_path, full_path, "-o", f"{path}/{file}.{format}"], shell=True)
                subprocess.run([shadercross_path, full_path, "-d", "JSON", "-o", f"{path}/{file}.{format}.json"], shell=True)
            name = file.split('.')[0]
            shader_list.append(name)


file_text = "// This is an autogenerated file do NOT edit.\n\n"
file_text += "#pragma once\n\n"
file_text += "#include \"shader_structures.h\"\n"
file_text += "#include \"SDL3/SDL_gpu.h\"\n\n"
embed_text = ""
embed_text += "static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here\n"
embed_text += "#pragma clang diagnostic push\n"
embed_text += "#pragma clang diagnostic ignored \"-Wc23-extensions\"\n\n"
enum_text = "enum class Shader {\n"
data_text = "constexpr ShaderData shader_data[] {\n"
load_dict : dict[str, str] = {}

def insert_embed(name : str, format : str, path : str):
    global embed_text
    embed_text += "constexpr u8 %s_%s[] {\n"%(name,format)
    embed_text += "\t#embed \"%s\"\n"%path
    embed_text += "};\n\n"

def process_json(path : str, name : str, format : str, stage : str):
    with open(path) as data:
        sdl_format = ""
        match format:
            case "spv":
                sdl_format = "SDL_GPU_SHADERFORMAT_SPIRV"
            case "msl":
                sdl_format = "SDL_GPU_SHADERFORMAT_MSL"
            case "dxil":
                sdl_format = "SDL_GPU_SHADERFORMAT_DXIL"
        sdl_stage = ""
        match stage:
            case "vert":
                sdl_stage = "SDL_GPU_SHADERSTAGE_VERTEX"
            case "frag":
                sdl_stage = "SDL_GPU_SHADERSTAGE_FRAGMENT"
        json_data = json.load(data)
        num_samplers = json_data["samplers"]
        num_storage_textures = json_data["storage_textures"]
        num_storage_buffers = json_data["storage_buffers"]
        num_uniform_buffers = json_data["uniform_buffers"]
        index = "\t{\n\tu8 index = static_cast<u8>(Shader::" + name.upper() + ");\n";
        info = "\tSDL_GPUShaderCreateInfo info {%s, %s, \"main\", %s, %s, %s, %s, %s, %s};\n"%(
            f"shader_data[index].{format}.size", f"shader_data[index].{format}.data", sdl_format, sdl_stage, num_samplers, num_storage_textures, num_storage_buffers, num_uniform_buffers)
        load_dict.update({format: index + info + "\tloaded_shaders[index] = SDL_CreateGPUShader(device, &info);\n\t}\n"})

for (root, dirs, files) in os.walk("..\\assets\\shaders"):
    for file in files:
        full_path = os.path.join(root, file)
        split = file.split('.')
        name = split[0]
        stage = split[1]
        format = split[-1]
        if format == "json":
            process_json(full_path, name, split[-2], stage)
            continue
        insert_embed(name, format, full_path)

def insert_enum(name : str):
    global enum_text
    enum_text += f"\t{name.upper()},\n"

def insert_data(name : str):
    global data_text
    spv = name + "_spv";
    mxl = name + "_msl"
    dxil = name + "_dxil"
    data_text += "\t{{%s, sizeof(%s)}, {%s, sizeof(%s)}, {%s, sizeof(%s)}},\n"%(spv, spv, mxl, mxl, dxil, dxil)

for shader in shader_list:
    insert_enum(shader)
    insert_data(shader)

embed_text += "#pragma clang diagnostic pop\n\n"
enum_text += "};\n\n"
data_text += "};\n\n"

header_load_text = ""
cpp_load_text = ""
for key, value in load_dict.items():
    cpp_load_text += "void create_%s_shaders(SDL_GPUDevice* device) {\n"%(key)
    cpp_load_text += value
    cpp_load_text += "};\n\n"
    header_load_text += "void create_%s_shaders(SDL_GPUDevice* device);\n"%(key)

file_text += embed_text;
file_text += enum_text;
file_text += data_text;
file_text += f"constexpr u8 number_of_shaders = {len(shader_list)};\n"
file_text += "extern SDL_GPUShader* loaded_shaders[number_of_shaders];\n\n"
file_text += header_load_text
with open("../source/shader_data.h", "w") as header:
    header.write(file_text)

cpp_text = "// This file is autogenerated! Do not edit!\n\n"
cpp_text += "#include \"shader_data.h\"\n\n"
cpp_text += "SDL_GPUShader* loaded_shaders[number_of_shaders]{};\n\n"
cpp_text += cpp_load_text
with open("../source/shader_data.cpp", "w") as cpp:
    cpp.write(cpp_text)
