import os

def get_files_of_type(type : str):
    found_files = []
    for (root, _dirs, files) in os.walk("..\\assets"):
        for file in files:
            split = file.split('.', 1)
            name = split[0].lower()
            extension = split[1]
            if extension != type: continue
            full_path = os.path.join(root, file);
            found_files.append((name, full_path))
    return found_files

def get_integer_constant_text(name : str, value : int):
    return f"constexpr int {name} = {value};"

class EmbedBuilder:
    def __init__(self, name : str):
        self.name = name
        self.paths : list[str] = []

    def get_name_from_path(self, path : str):
        return path.split('.')[-2].split('\\')[-1].lower()

    def add_embed(self, path : str):
        self.paths.append(path)

    def get_embed_text(self):
        result =  """static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here
#pragma clang diagnostic push
#pragma clang diagnostic ignored \"-Wc23-extensions\"
#ifdef FILE_EMBED

"""
        for path in self.paths:
            result += "constexpr char %s[] {\n\t#embed \"%s\"\n};\n\n"%(self.get_name_from_path(path), path)
        result += "#pragma clang diagnostic pop\n"
        result += "#endif\n"

        result += "#ifndef FILE_EMBED\n"
        for path in self.paths:
            result += "constexpr char %s[] {};\n\n"%(self.get_name_from_path(path))
        result += "#endif"

        return result

    def get_data_array_text(self):
        result = "constexpr const char* %s[] {\n"%(self.name + "_data")
        for path in self.paths:
            result += f"\t{self.get_name_from_path(path)},\n"
        result += "};"
        return result

    def get_size_array_text(self):
        result = "constexpr int %s[] {\n"%(self.name + "_sizes")
        for path in self.paths:
            result += f"\tsizeof({self.get_name_from_path(path)}),\n"
        result += "};"
        return result

class EnumBuilder:
    def __init__(self, name : str):
        self.name = name
        self.entries : list[str] = []

    def add_entry(self, entry : str):
        self.entries.append(entry.upper().replace(' ', '_'))

    def get_text(self):
        return "enum class %s {\n\t"%self.name + ",\n\t".join(self.entries) + "\n};"

class ArrayBuilder:
    def __init__(self, type : str, name : str):
        self.type = type
        self.name = name
        self.entries : list[str] = []

    def add_entry(self, entry : str):
        self.entries.append(entry)

    def get_text(self):
        return "constexpr %s %s[] {\n\t"%(self.type, self.name) + ",\n\t".join(self.entries) + "\n};"

def build_header(builders, includes : list[str]):
    text = "// This is an autogenerated file. Do not edit!\n\n"
    text += "#pragma once\n\n"

    for include in includes:
        text += f"#include \"{include}\"\n"

    if len(includes) > 0:
        text += "\n"

    for builder in builders:
        if type(builder) is EmbedBuilder:
            text += builder.get_embed_text() + "\n\n"
            text += builder.get_data_array_text() + "\n\n"
            text += builder.get_size_array_text()
        elif type(builder) is str:
            text += builder
        else:
            text += builder.get_text()
        text += "\n\n"

    return text
