import os
import json
from PIL import Image

file_text = "// This is an autogenerated file. Do not edit!\n\n"
file_text += "#pragma once\n"
file_text += "#import \"physics.h\"\n\n"

for (root, dirs, files) in os.walk("..\\assets"):
    for file in files:
        split = file.split('.', 1)
        name = split[0] # remove file extension
        extension = split[1]
        full_path = os.path.join(root, file);

        if extension == "png":
            json_path = full_path.replace("png", "json")
            if os.path.isfile(json_path):
                with open(json_path) as data:
                    data = json.load(data)
                    list = data["frames"]
                    AABB_left = -1;
                    AABB_top = -1;
                    AABB_right = -1;
                    AABB_bottom = -1;
                    for entry in list:
                        image_name = entry["filename"].upper().replace(" ", "_")

                        if "DOWN_RIGHT_LEG_1" in image_name:
                            image_x = entry["frame"]["x"]
                            image_y = entry["frame"]["y"]
                            image_w = entry["frame"]["w"]
                            image_h = entry["frame"]["h"]
                            image = Image.open(full_path)
                            cropped_image = image.crop((image_x, image_y, image_x + image_w, image_y + image_h))
                            bounding_box = cropped_image.getbbox()
                            if bounding_box != None:
                                AABB_right = bounding_box[2]
                                AABB_bottom = bounding_box[3]
                            AABB_top = AABB_bottom - 25
                        if "DOWN_LEFT_LEG_1" in image_name:
                            image_x = entry["frame"]["x"]
                            image_y = entry["frame"]["y"]
                            image_w = entry["frame"]["w"]
                            image_h = entry["frame"]["h"]
                            image = Image.open(full_path)
                            cropped_image = image.crop((image_x, image_y, image_x + image_w, image_y + image_h))
                            bounding_box = cropped_image.getbbox()
                            if bounding_box != None:
                                AABB_left = bounding_box[0]

                    if AABB_left != -1 and AABB_right != -1:
                        file_text += "constexpr BoxColliderComponent %s_COLLIDER = {{%s, %s}, {%s, %s}};\n"%(name.upper(), AABB_left, AABB_top, AABB_right, AABB_bottom)


with open("../src/collider_data.h", "w") as header:
    header.write(file_text)
