from PIL import Image, ImageFont, ImageDraw

font_path = "C:/Projects/ILATSPIDK/assets/atkinson_hyperlegible.ttf"
english_start = 32
number_of_english_characters = 95
last_english_character = english_start + number_of_english_characters - 1

file_text = "// This file is autogenerated do not edit please\n\n"
file_text += "#pragma once\n\n"
file_text += "#include \"font_structures.h\"\n\n"
file_text += "constexpr Font fonts[] {\n"

number_of_fonts = 0

width_map = []

def create_font(name : str, size, width, height):
    global font_path
    global number_of_english_characters
    global width_map
    width_map = []
    font = ImageFont.truetype(font_path, size)
    image = Image.new('LA', (width * number_of_english_characters, height))
    draw = ImageDraw.Draw(image)
    for i in range(number_of_english_characters):
        text = chr(english_start + i);
        width_map.append(draw.textlength(text, font=font))
        draw.text((i * width + 3, 0), text, font=font, fill="white") # Add a little spacing of 3 from the left
    output_path = f"C:/Projects/ILATSPIDK/assets/atlas/{name}_font.png"
    image.save(output_path)

    global file_text
    file_text += "\t{%s, %s, %s, %s},\n"%(f"ImageFile::{name.upper()}_FONT_IMAGE", size, width, height)

    global number_of_fonts
    number_of_fonts += 1

create_font("small", 16, 16, 32)
create_font("medium", 24, 24, 48)
create_font("large", 48, 48, 96)

file_text += "};\n\n"
file_text += f"constexpr int NUMBER_OF_FONTS = {number_of_fonts};\n"
file_text += f"constexpr int ENGLISH_STARTING_CHARACTER = {english_start};\n\n"

file_text += "constexpr float character_widths[] = {"
for width in width_map:
    file_text += f" {width},"
file_text += "};\n\n"

# Adapted from https://github.com/adobe-type-tools/kern-dump/blob/main/getKerningPairsFromOTF.py
from fontTools import ttLib, agl # pip install fonttools

font_data = ttLib.TTFont(font_path)
glyph_position_table = font_data['GPOS'].table
feature_record = glyph_position_table.FeatureList.FeatureRecord
kern_lookup_list = []
for feature in feature_record:
    if feature.FeatureTag == 'kern':
        for feature_item in feature.Feature.LookupListIndex:
            if feature_item not in kern_lookup_list:
                kern_lookup_list.append(feature_item)
lookup_list = glyph_position_table.LookupList
lookups = []
for index in sorted(kern_lookup_list):
    lookup = lookup_list.Lookup[index]
    if lookup.LookupType in [2,9]:
        lookups.append(lookup)
pairs = []
for lookup in lookups:
    for item in lookup.SubTable:
        if item.LookupType == 9 and item.ExtensionLookupType == 2:
            item = item.ExtSubTable
        pairs.append(item)
kerning_pairs = {}
for pair_position in pairs:
    if pair_position.Format == 1:
        for index, pair_set in enumerate(pair_position.PairSet):
            for item in pair_set.PairValueRecord:
                first_glyph = agl.toUnicode(pair_position.Coverage.glyphs[index])
                second_glyph = agl.toUnicode(item.SecondGlyph)
                if (ord(first_glyph) < english_start or ord(first_glyph) > last_english_character): continue
                if (ord(second_glyph) < english_start or ord(second_glyph) > last_english_character): continue
                pair = first_glyph, second_glyph
                value_format = pair_position.ValueFormat1
                if value_format == 5: # right-to-left kerning
                    x_placement = item.Value1.XPlacement
                    x_advance = item.Value1.XAdvance
                    kern_value = f'<x_placement 0 {x_advance} 0>'
                elif value_format == 0: # right-to-left pair with value <0 0 0 0>
                    kern_value = "<0 0 0 0>"
                elif value_format == 4: # left-to-right kerning
                    kern_value = item.Value1.XAdvance
                else:
                    continue
                kerning_pairs[pair] = kern_value
# end of copying from the internet
print(kerning_pairs)

kerning_data = {} # want to convert FROM dictionary of tuple->number TO dictionary of dictionary of number
for pair in kerning_pairs.keys():
    first = ord(pair[0]) - english_start
    second = ord(pair[1]) - english_start
    if first not in kerning_data:
        kerning_data[first] = {}
    kerning_data[first][second] = kerning_pairs[pair]

print(kerning_data)

file_text += "constexpr i8 kerning[][%s] = {\n"%number_of_english_characters;
for i in range(number_of_english_characters):
    file_text += "\t {"
    for j in range(number_of_english_characters):
        if i in kerning_data and j in kerning_data[i]:
            file_text += f"{kerning_data[i][j]}, "
        else:
            file_text += "0, "
    file_text += "},\n"
file_text += "};\n\n"

with open("../source/font_data.h", "w") as header:
    header.write(file_text)
