import re
import os

output = "// THIS IS AUTOGENERATED FILE NO DO NOT EDIT\n\n"
output += "#pragma once\n\n"
output += "#include \"../basic/vector2.h\"\n"
output += "#include \"../basic/shapes.h\"\n\n"
output += "namespace LD {\n"

scene_location = "C:/Projects/Godot Projects/level-editor/scenes"

for (root, _dirs, files) in os.walk(scene_location):
    for file in files:
        split = file.split('.', 1)
        scene_name = split[0].lower()
        extension = split[1]
        full_path = os.path.join(root, file)
        if extension == "tscn":
            with open(full_path, "r") as file:
                text = file.read()
                for found in re.finditer('node name="(.*?)" type="(.*?)".*\nposition = Vector2\\((.*?), (.*?)\\)', text):
                    name = found.group(1)
                    type = found.group(2)
                    x = float(found.group(3))
                    y = -float(found.group(4))
                    if type == "CollisionShape2D":
                        rectangle_name = re.findall(f'node name="{name}".*\n.*\nshape = SubResource\\("(.*?)"\\)', text).pop()
                        size = re.findall(f'id="{rectangle_name}".*\nsize = Vector2\\((.*?), (.*?)\\)', text).pop()
                        w = float(size[0])
                        h = float(size[1])
                        output += "constexpr Box %s = {{%s, %s}, {%s, %s}};\n"%(scene_name.upper() + "_" + name.upper(), x - w / 2, y + h / 2, x + w / 2, y - h / 2)
                    else:
                        output += "constexpr Vector2 %s = {%s, %s};\n"%(scene_name.upper() + "_" + name.upper(), x, y)
                for found in re.finditer('node name="(.*?)" type="Polygon2D".*\npolygon = PackedVector2Array\\((.*?)\\)', text):
                    name = found.group(1)
                    positions = found.group(2).split(", ")
                    position_values = [int(value) for value in positions]
                    position_text = ""
                    i = 0
                    while i < len(position_values):
                        position_text += "Vector2{"
                        position_text += str(position_values[i])
                        position_text += ","
                        i = i+1;
                        position_text += str(-position_values[i])
                        position_text += "},"
                        i = i+1
                    output += "constexpr Polygon %s = {{%s}};\n"%(scene_name.upper() + "_" + name.upper(), position_text)
output += "}\n"

with open("../source/data/position_data.h", "w") as header:
    header.write(output)
