from PIL import Image, ImageFont, ImageDraw

font_path = "C:/Projects/ILATSPIDK/assets/atkinson_hyperlegible.ttf"
english_start = 32
number_of_english_characters = 95
last_english_character = english_start + number_of_english_characters - 1

file_text = "// This file is autogenerated do not edit please\n\n"
file_text += "#pragma once\n\n"
file_text += "#include \"font_structures.h\"\n\n"
file_text += "constexpr Font fonts[] {\n"

number_of_fonts = 0

width_map = []

def create_font(name : str, size : int):
    global font_path
    global number_of_english_characters
    global width_map
    width_map = []
    font = ImageFont.truetype(font_path, size)
    width : int = size
    height : int = round(width * 1.5)
    image = Image.new('LA', (width * number_of_english_characters, height))
    draw = ImageDraw.Draw(image)
    for i in range(number_of_english_characters):
        text = chr(english_start + i);
        width_map.append(draw.textlength(text, font=font))
        draw.text((i * width + 3, 0), text, font=font, fill="white") # Add a little spacing of 3 from the left
    output_path = f"C:/Projects/ILATSPIDK/assets/atlas/{name}_font.png"
    image.save(output_path)

    global file_text
    file_text += "\t{%s, %s, %s, %s},\n"%(f"ImageFile::{name.upper()}_FONT_IMAGE", size, width, height)

    global number_of_fonts
    number_of_fonts += 1

create_font("extra_small", 8)
create_font("small", 16)
create_font("small_medium", 20)
create_font("medium", 24)
create_font("medium_large", 36)
create_font("large", 48)
create_font("very_large", 72)

file_text += "};\n\n"
file_text += f"constexpr int NUMBER_OF_FONTS = {number_of_fonts};\n"
file_text += f"constexpr int ENGLISH_STARTING_CHARACTER = {english_start};\n\n"

file_text += "constexpr float character_widths[] = {"
for width in width_map:
    file_text += f" {width},"
file_text += "};\n\n"

from fontTools import agl # pip install fonttools
from external.getKerningPairsFromOTF import OTFKernReader # https://github.com/adobe-type-tools/kern-dump/blob/main/getKerningPairsFromOTF.py
kerning_data = {} # want a dictionary of dictionary of number
kern_reader = OTFKernReader(font_path)
#print(kern_reader.kerningPairs)
for pair in kern_reader.kerningPairs:
    first_glyph = agl.toUnicode(pair[0])
    if not english_start <= ord(first_glyph) <= last_english_character: continue
    second_glyph = agl.toUnicode(pair[1])
    if not english_start <= ord(second_glyph) <= last_english_character: continue
    first_index = ord(first_glyph) - english_start
    second_index = ord(second_glyph) - english_start
    if first_index not in kerning_data:
        kerning_data[first_index] = {}
    kerning_data[first_index][second_index] = kern_reader.kerningPairs[pair]
#print(kerning_data)

file_text += "constexpr i8 kerning[][%s] = {\n"%number_of_english_characters;
for i in range(number_of_english_characters):
    file_text += "\t {"
    for j in range(number_of_english_characters):
        if i in kerning_data and j in kerning_data[i]:
            file_text += f"{kerning_data[i][j]}, "
        else:
            file_text += "0, "
    file_text += "},\n"
file_text += "};\n\n"

with open("../source/font_data.h", "w") as header:
    header.write(file_text)
