import re

scene_location = "C:/Projects/Godot Projects/level-editor/scene.tscn"

output = "// THIS IS AUTOGENERATED FILE NO DO NOT EDIT\n\n"
output += "#pragma once\n\n"
output += "#include \"../engine/vector2.h\"\n"
output += "#include <initializer_list>\n\n"

with open(scene_location, "r") as file:
    text = file.read()
    for found in re.finditer('node name="(.*?)" type="(.*?)".*\nposition = Vector2\\((.*?), (.*?)\\)', text):
        name = found.group(1)
        type = found.group(2)
        x = float(found.group(3))
        y = -float(found.group(4))
        if type == "CollisionShape2D":
            rectangle_name = re.findall(f'node name="{name}".*\n.*\nshape = SubResource\\("(.*?)"\\)', text).pop()
            size = re.findall(f'id="{rectangle_name}".*\nsize = Vector2\\((.*?), (.*?)\\)', text).pop()
            w = float(size[0])
            h = float(size[1])
            output += "constexpr Box %s = {{%s, %s}, {%s, %s}};\n"%(name.upper(), x - w / 2, y + h / 2, x + w / 2, y - h / 2)
        else:
            output += "constexpr Vector2 %s = {%s, %s};\n"%(name.upper(), x, y)
    for found in re.finditer('node name="(.*?)" type="Polygon2D".*\npolygon = PackedVector2Array\\((.*?)\\)', text):
        name = found.group(1)
        positions = found.group(2).split(", ")
        position_values = [int(value) for value in positions]
        position_text = ""
        i = 0
        while i < len(position_values):
            position_text += "{"
            position_text += str(position_values[i])
            position_text += ","
            i = i+1;
            position_text += str(-position_values[i])
            position_text += "},"
            i = i+1
        output += "constexpr std::initializer_list<Vector2> %s = {%s};\n"%(name.upper(), position_text)

with open("../source/data/position_data.h", "w") as header:
    header.write(output)
