import os

header_text = "// This is an autogenerated file. Do not edit!\n\n"
header_text += "#pragma once\n\n"

header_text += "static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here\n\n"
header_text += "#pragma clang diagnostic push\n"
header_text += "#pragma clang diagnostic ignored \"-Wc23-extensions\"\n\n"

image_enum_text = "enum class ImageAsset {\n"
image_array_text = "constexpr const inline char* image_data[] {\n"
image_size_text = "constexpr int image_sizes[] {\n"

number_of_images = 0

for (root, dirs, files) in os.walk("..\\assets"):
    for file in files:
        split = file.split('.', 1)
        name = split[0] # remove file extension
        extension = split[1]
        full_path = os.path.join(root, file);
        header_text += "constexpr inline char %s[] { \n\t#embed \"%s\"\n};\n\n"%(name, full_path)

        if extension == "png":
            image_enum_text += "\t" + name.upper() + "_IMAGE,\n"
            image_array_text += "\t%s,\n"%name
            image_size_text += "\tsizeof(" + name + "),\n"
            number_of_images += 1

header_text += "#pragma clang diagnostic pop\n\n"

image_enum_text += "};\n\n"
header_text += image_enum_text

image_array_text += "};\n\n"
header_text += image_array_text

image_size_text += "};\n\n"
header_text += image_size_text

header_text += "constexpr int NUMBER_OF_IMAGES = %s;"%number_of_images

with open("../src/game_assets.h", "w") as header:
    header.write(header_text)
