import os
import json

image_file_text = "// This is an autogenerated file. Do not edit!\n\n"
image_file_text += "#pragma once\n\n"
image_file_text += "static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here\n\n"
image_file_text += "#pragma clang diagnostic push\n"
image_file_text += "#pragma clang diagnostic ignored \"-Wc23-extensions\"\n\n"

audio_file_text = "// This is an autogenerated file. Do not edit!\n\n"
audio_file_text += "#pragma once\n\n"
audio_file_text += "static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here\n\n"
audio_file_text += "#pragma clang diagnostic push\n"
audio_file_text += "#pragma clang diagnostic ignored \"-Wc23-extensions\"\n\n"

image_enum_text = "enum class ImageAsset {\n"
image_array_text = "constexpr const inline char* image_data[] {\n"
image_size_text = "constexpr int image_sizes[] {\n"
number_of_images = 0

atlas_struct_text = "struct AtlasData {\n\t"
atlas_struct_text += "int x;\n\t"
atlas_struct_text += "int y;\n\t"
atlas_struct_text += "int w;\n\t"
atlas_struct_text += "int h;\n"
atlas_struct_text += "};\n\n"
atlas_enum_text = "enum class AtlasIndex {\n"
atlas_data_text = "constexpr AtlasData atlas_data[] {\n"
atlas_to_image_text = "template<AtlasIndex atlas_index> consteval int get_atlas_image() {\n\t"
atlas_to_image_text += "constexpr int index = static_cast<int>(atlas_index);\n\n\t"
atlas_to_image_text += "if constexpr (index < 0) return -1;\n"
number_of_atlas = 0

audio_enum_text = "enum class AudioAsset {\n"
audio_array_text = "constexpr const inline char* audio_data[] {\n"
audio_size_text = "constexpr int audio_sizes[] {\n"
number_of_sounds = 0

for (root, dirs, files) in os.walk("..\\assets"):
    for file in files:
        split = file.split('.', 1)
        name = split[0] # remove file extension
        extension = split[1]
        full_path = os.path.join(root, file);

        if extension == "ttf":
            image_file_text += "constexpr inline char %s[] { \n\t#embed \"%s\"\n};\n\n"%(name, full_path)

        if extension == "png":
            image_file_text += "constexpr inline char %s[] { \n\t#embed \"%s\"\n};\n\n"%(name, full_path)
            image_enum_text += "\t" + name.upper() + "_IMAGE,\n"
            image_array_text += "\t%s,\n"%name
            image_size_text += "\tsizeof(" + name + "),\n"
            number_of_images += 1

            json_path = full_path.replace("png", "json")
            if os.path.isfile(json_path):
                with open(json_path) as data:
                    data = json.load(data)
                    list = data["frames"]
                    for entry in list:
                        image_name = entry["filename"].upper().replace(" ", "_")
                        image_x = entry["frame"]["x"]
                        image_y = entry["frame"]["y"]
                        image_w = entry["frame"]["w"]
                        image_h = entry["frame"]["h"]
                        atlas_enum_text += "\t" + image_name + ",\n"
                        atlas_data_text += "\t{%s, %s, %s, %s},\n"%(image_x,image_y,image_w,image_h)
                        number_of_atlas += 1
                    atlas_to_image_text += "\telse if constexpr (index < %s) return %s;\n"%(number_of_atlas, number_of_images - 1)

        if extension == "wav":
            audio_file_text += "constexpr inline char %s[] { \n\t#embed \"%s\"\n};\n\n"%(name, full_path)
            audio_enum_text += "\t" + name.upper() + "_AUDIO,\n"
            audio_array_text += "\t%s,\n"%name
            audio_size_text += "\tsizeof(" + name + "),\n"
            number_of_sounds += 1

image_file_text += "#pragma clang diagnostic pop\n\n"
audio_file_text += "#pragma clang diagnostic pop\n\n"

image_enum_text += "};\n\n"
image_file_text += image_enum_text
image_array_text += "};\n\n"
image_file_text += image_array_text
image_size_text += "};\n\n"
image_file_text += image_size_text
image_file_text += "constexpr int NUMBER_OF_IMAGES = %s;\n\n\n"%number_of_images

atlas_enum_text += "};\n\n"
image_file_text += atlas_enum_text
image_file_text += atlas_struct_text
atlas_data_text += "};\n\n"
image_file_text += atlas_data_text
atlas_to_image_text += "\treturn -1;\n"
atlas_to_image_text += "}\n\n"
image_file_text += atlas_to_image_text

audio_enum_text += "};\n\n"
audio_file_text += audio_enum_text
audio_array_text += "};\n\n"
audio_file_text += audio_array_text
audio_size_text += "};\n\n"
audio_file_text += audio_size_text
audio_file_text += "constexpr int NUMBER_OF_SOUNDS = %s;\n\n\n"%number_of_sounds

with open("../src/image_assets.h", "w") as header:
    header.write(image_file_text)

with open("../src/audio_assets.h", "w") as header:
    header.write(audio_file_text)
