// This is an autogenerated file. Do not edit!

#pragma once

static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"

constexpr inline char success[] { 
	#embed "..\assets\success.wav"
};

#pragma clang diagnostic pop

enum class AudioAsset {
	SUCCESS_AUDIO,
};

constexpr const inline char* audio_data[] {
	success,
};

constexpr int audio_sizes[] {
	sizeof(success),
};

constexpr int NUMBER_OF_SOUNDS = 1;


