// This is an autogenerated file. Do not edit!

#pragma once

static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"

constexpr inline char AtkinsonHyperlegible[] { 
	#embed "..\assets\AtkinsonHyperlegible.ttf"
};

constexpr inline char Kerry[] { 
	#embed "..\assets\Kerry.png"
};

constexpr inline char test_background[] { 
	#embed "..\assets\test_background.png"
};

constexpr inline char test_button[] { 
	#embed "..\assets\test_button.png"
};

constexpr inline char test_image[] { 
	#embed "..\assets\test_image.png"
};

#pragma clang diagnostic pop
