// This is an autogenerated file. Do not edit!

#pragma once

static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"

constexpr inline char atkinson_hyperlegible[] { 
	#embed "..\assets\atkinson_hyperlegible.ttf"
};

constexpr inline char captain_orange[] { 
	#embed "..\assets\captain_orange.png"
};

constexpr inline char kerry[] { 
	#embed "..\assets\kerry.png"
};

constexpr inline char test_background[] { 
	#embed "..\assets\test_background.png"
};

constexpr inline char test_button[] { 
	#embed "..\assets\test_button.png"
};

constexpr inline char test_atlas[] { 
	#embed "..\assets\atlas\test_atlas.png"
};

#pragma clang diagnostic pop

enum class ImageAsset {
	CAPTAIN_ORANGE_IMAGE,
	KERRY_IMAGE,
	TEST_BACKGROUND_IMAGE,
	TEST_BUTTON_IMAGE,
	TEST_ATLAS_IMAGE,
};

constexpr const inline char* image_data[] {
	captain_orange,
	kerry,
	test_background,
	test_button,
	test_atlas,
};

constexpr int image_sizes[] {
	sizeof(captain_orange),
	sizeof(kerry),
	sizeof(test_background),
	sizeof(test_button),
	sizeof(test_atlas),
};

constexpr int NUMBER_OF_IMAGES = 5;


enum class AtlasIndex {
	KERRY_DOWN_CAPE_1,
	KERRY_DOWN_CAPE_2,
	KERRY_DOWN_CAPE_3,
	KERRY_DOWN_CAPE_4,
	KERRY_DOWN_CAPE_5,
	KERRY_DOWN_CAPE_6,
	KERRY_DOWN_RIGHT_LEG_1,
	KERRY_DOWN_RIGHT_LEG_2,
	KERRY_DOWN_RIGHT_LEG_3,
	KERRY_DOWN_RIGHT_LEG_4,
	KERRY_DOWN_LEFT_LEG_1,
	KERRY_DOWN_LEFT_LEG_2,
	KERRY_DOWN_LEFT_LEG_3,
	KERRY_DOWN_LEFT_LEG_4,
	KERRY_DOWN_FLOWER_1,
	KERRY_DOWN_FLOWER_2,
	KERRY_DOWN_FLOWER_3,
	KERRY_DOWN_FLOWER_4,
	KERRY_DOWN_FLOWER_5,
	KERRY_DOWN_FLOWER_6,
	KERRY_DOWN_BODY_1,
	KERRY_DOWN_BODY_2,
	KERRY_DOWN_BODY_3,
	KERRY_DOWN_BODY_4,
	KERRY_RIGHT_FLOWER_1,
	KERRY_RIGHT_FLOWER_2,
	KERRY_RIGHT_FLOWER_3,
	KERRY_RIGHT_FLOWER_4,
	KERRY_RIGHT_FLOWER_5,
	KERRY_RIGHT_FLOWER_6,
	KERRY_RIGHT_LEFT_LEG_1,
	KERRY_RIGHT_LEFT_LEG_2,
	KERRY_RIGHT_LEFT_LEG_3,
	KERRY_RIGHT_LEFT_LEG_4,
	KERRY_RIGHT_RIGHT_LEG_1,
	KERRY_RIGHT_RIGHT_LEG_2,
	KERRY_RIGHT_RIGHT_LEG_3,
	KERRY_RIGHT_RIGHT_LEG_4,
	KERRY_RIGHT_BODY_1,
	KERRY_RIGHT_BODY_2,
	KERRY_RIGHT_BODY_3,
	KERRY_RIGHT_BODY_4,
	KERRY_RIGHT_CAPE_1,
	KERRY_RIGHT_CAPE_2,
	KERRY_RIGHT_CAPE_3,
	KERRY_RIGHT_CAPE_4,
	KERRY_RIGHT_CAPE_5,
	KERRY_RIGHT_CAPE_6,
	KERRY_LEFT_FLOWER_1,
	KERRY_LEFT_FLOWER_2,
	KERRY_LEFT_FLOWER_3,
	KERRY_LEFT_FLOWER_4,
	KERRY_LEFT_FLOWER_5,
	KERRY_LEFT_FLOWER_6,
	KERRY_LEFT_RIGHT_LEG_1,
	KERRY_LEFT_RIGHT_LEG_2,
	KERRY_LEFT_RIGHT_LEG_3,
	KERRY_LEFT_RIGHT_LEG_4,
	KERRY_LEFT_LEFT_LEG_1,
	KERRY_LEFT_LEFT_LEG_2,
	KERRY_LEFT_LEFT_LEG_3,
	KERRY_LEFT_LEFT_LEG_4,
	KERRY_LEFT_BODY_1,
	KERRY_LEFT_BODY_2,
	KERRY_LEFT_BODY_3,
	KERRY_LEFT_BODY_4,
	KERRY_LEFT_CAPE_1,
	KERRY_LEFT_CAPE_2,
	KERRY_LEFT_CAPE_3,
	KERRY_LEFT_CAPE_4,
	KERRY_LEFT_CAPE_5,
	KERRY_LEFT_CAPE_6,
	KERRY_UP_FLOWER_1,
	KERRY_UP_FLOWER_2,
	KERRY_UP_FLOWER_3,
	KERRY_UP_FLOWER_4,
	KERRY_UP_FLOWER_5,
	KERRY_UP_FLOWER_6,
	KERRY_UP_BODY_1,
	KERRY_UP_BODY_2,
	KERRY_UP_BODY_3,
	KERRY_UP_LEFT_LEG_1,
	KERRY_UP_LEFT_LEG_2,
	KERRY_UP_LEFT_LEG_3,
	KERRY_UP_LEFT_LEG_4,
	KERRY_UP_RIGHT_LEG_1,
	KERRY_UP_RIGHT_LEG_2,
	KERRY_UP_RIGHT_LEG_3,
	KERRY_UP_RIGHT_LEG_4,
	KERRY_UP_CAPE_1,
	KERRY_UP_CAPE_2,
	KERRY_UP_CAPE_3,
	KERRY_UP_CAPE_4,
	KERRY_UP_CAPE_5,
	KERRY_UP_CAPE_6,
};

struct AtlasData {
	int x;
	int y;
	int w;
	int h;
};

constexpr AtlasData atlas_data[] {
	{0, 0, 200, 300},
	{200, 0, 200, 300},
	{400, 0, 200, 300},
	{600, 0, 200, 300},
	{800, 0, 200, 300},
	{1000, 0, 200, 300},
	{1200, 0, 200, 300},
	{1400, 0, 200, 300},
	{1600, 0, 200, 300},
	{1800, 0, 200, 300},
	{0, 300, 200, 300},
	{200, 300, 200, 300},
	{400, 300, 200, 300},
	{600, 300, 200, 300},
	{800, 300, 200, 300},
	{1000, 300, 200, 300},
	{1200, 300, 200, 300},
	{1400, 300, 200, 300},
	{1600, 300, 200, 300},
	{1800, 300, 200, 300},
	{0, 600, 200, 300},
	{200, 600, 200, 300},
	{400, 600, 200, 300},
	{600, 600, 200, 300},
	{800, 600, 200, 300},
	{1000, 600, 200, 300},
	{1200, 600, 200, 300},
	{1400, 600, 200, 300},
	{1600, 600, 200, 300},
	{1800, 600, 200, 300},
	{0, 900, 200, 300},
	{200, 900, 200, 300},
	{400, 900, 200, 300},
	{600, 900, 200, 300},
	{800, 900, 200, 300},
	{1000, 900, 200, 300},
	{1200, 900, 200, 300},
	{1400, 900, 200, 300},
	{1600, 900, 200, 300},
	{1800, 900, 200, 300},
	{0, 1200, 200, 300},
	{200, 1200, 200, 300},
	{400, 1200, 200, 300},
	{600, 1200, 200, 300},
	{800, 1200, 200, 300},
	{1000, 1200, 200, 300},
	{1200, 1200, 200, 300},
	{1400, 1200, 200, 300},
	{1600, 1200, 200, 300},
	{1800, 1200, 200, 300},
	{0, 1500, 200, 300},
	{200, 1500, 200, 300},
	{400, 1500, 200, 300},
	{600, 1500, 200, 300},
	{800, 1500, 200, 300},
	{1000, 1500, 200, 300},
	{1200, 1500, 200, 300},
	{1400, 1500, 200, 300},
	{1600, 1500, 200, 300},
	{1800, 1500, 200, 300},
	{0, 1800, 200, 300},
	{200, 1800, 200, 300},
	{400, 1800, 200, 300},
	{600, 1800, 200, 300},
	{800, 1800, 200, 300},
	{1000, 1800, 200, 300},
	{1200, 1800, 200, 300},
	{1400, 1800, 200, 300},
	{1600, 1800, 200, 300},
	{1800, 1800, 200, 300},
	{0, 2100, 200, 300},
	{200, 2100, 200, 300},
	{400, 2100, 200, 300},
	{600, 2100, 200, 300},
	{800, 2100, 200, 300},
	{1000, 2100, 200, 300},
	{1200, 2100, 200, 300},
	{1400, 2100, 200, 300},
	{1600, 2100, 200, 300},
	{1800, 2100, 200, 300},
	{0, 2400, 200, 300},
	{200, 2400, 200, 300},
	{400, 2400, 200, 300},
	{600, 2400, 200, 300},
	{800, 2400, 200, 300},
	{1000, 2400, 200, 300},
	{1200, 2400, 200, 300},
	{1400, 2400, 200, 300},
	{1600, 2400, 200, 300},
	{1800, 2400, 200, 300},
	{0, 2700, 200, 300},
	{200, 2700, 200, 300},
	{400, 2700, 200, 300},
	{600, 2700, 200, 300},
	{800, 2700, 200, 300},
};

template<AtlasIndex atlas_index> consteval int get_atlas_image() {
	constexpr int index = static_cast<int>(atlas_index);

	if constexpr (index < 0) return -1;
	else if constexpr (index < 95) return 4;
	return -1;
}

