// This is an autogenerated file--do not edit!!

#pragma once
#include "dialog_structures.h"

enum class Speaker {
	WIZARD,
	LADYBUG,
	NIELON,
	KERRY,
	TABLE,
};

void give_flower();
bool has_flower();
bool has_cat();

constexpr Dialog SAMPLE_DIALOG[] {
/* 001 */	DialogLine { "Do you know where to find the orb?", Speaker::WIZARD },
/* 002 */	DialogChoice { "Orange: Yes!", 5, nullptr },
/* 003 */	DialogJump { 0 },
/* 004 */	DialogJump { 29 },
/* 005 */	DialogChoice { "Orange: No", 0, nullptr },
/* 006 */	DialogLine { "Where is it?", Speaker::WIZARD },
/* 007 */	DialogChoice { "Orange: It's off the coast of Kamlin?", 22, nullptr },
/* 008 */	DialogLine { "And where is that?", Speaker::WIZARD },
/* 009 */	DialogChoice { "Orange: Huh?", 12, nullptr },
/* 010 */	DialogLine { "Don't be smart with me, dolt!", Speaker::WIZARD },
/* 011 */	DialogJump { 14 },
/* 012 */	DialogChoice { "Orange: I don't know what you're talking about!", 0, nullptr },
/* 013 */	DialogLine { "You will!", Speaker::WIZARD },
/* 014 */	DialogLine { "Shut up!", Speaker::LADYBUG },
/* 015 */	DialogLine { "That's no way to talk to me.", Speaker::WIZARD },
/* 016 */	DialogChoice { "Ladybug: Shut up!!", 19, nullptr },
/* 017 */	DialogJump { 0 },
/* 018 */	DialogJump { 21 },
/* 019 */	DialogChoice { "Orange: Haha!", 0, nullptr },
/* 020 */	DialogJump { 1 },
/* 021 */	DialogJump { 29 },
/* 022 */	DialogChoice { "Orange: It's behind you?", 26, nullptr },
/* 023 */	DialogLine { "Wrong!", Speaker::WIZARD },
/* 024 */	DialogJump { 0 },
/* 025 */	DialogJump { 29 },
/* 026 */	DialogChoice { "Orange: It's in the museum of modern political science!", 0, nullptr },
/* 027 */	DialogLine { "Yes!", Speaker::WIZARD },
/* 028 */	DialogJump { 0 },
/* 029 */	DialogJump { 0 },
};

constexpr Dialog SAMPLE_DIALOGUE[] {
/* 001 */	DialogLine { "Ah, there we are. Can you hear me?", Speaker::NIELON },
/* 002 */	DialogChoice { "Kerry: Yes, I can", 5, nullptr },
/* 003 */	DialogLine { "Excellent! Let's proceed.", Speaker::NIELON },
/* 004 */	DialogJump { 10 },
/* 005 */	DialogChoice { "Kerry: No, I can't", 0, nullptr },
/* 006 */	DialogLine { "Oh boy that's no good. Let me try something...", Speaker::NIELON },
/* 007 */	DialogLine { "Alright.", Speaker::KERRY },
/* 008 */	DialogLine { "Okay now can you hear me?", Speaker::NIELON },
/* 009 */	DialogJump { 2 },
/* 010 */	DialogLine { "Do you have that flower in your inventory?", Speaker::NIELON },
/* 011 */	DialogCheck { has_flower, 15 },
/* 012 */	DialogLine { "Yes", Speaker::KERRY },
/* 013 */	DialogJump { 0 },
/* 014 */	DialogJump { 18 },
/* 015 */	DialogChoice { "", 0, nullptr },
/* 016 */	DialogLine { "No", Speaker::KERRY },
/* 017 */	DialogFunction { give_flower },
/* 018 */	DialogLine { "Chungus.", Speaker::NIELON },
/* 019 */	DialogJump { 0 },
};

constexpr Dialog TABLE_DIALOG[] {
/* 001 */	DialogLine { "I'm a table!", Speaker::TABLE },
/* 002 */	DialogChoice { "Kerry: You sure look like one.", 14, nullptr },
/* 003 */	DialogLine { "I sure do!", Speaker::TABLE },
/* 004 */	DialogLine { "...", Speaker::KERRY },
/* 005 */	DialogLine { "Would you like to come in and have a drink?", Speaker::TABLE },
/* 006 */	DialogChoice { "Kerry: Come in where?", 10, nullptr },
/* 007 */	DialogLine { "Into my home of course!", Speaker::TABLE },
/* 008 */	DialogJump { 6 },
/* 009 */	DialogJump { 13 },
/* 010 */	DialogChoice { "Kerry: Uhhh... sure", 0, nullptr },
/* 011 */	DialogLine { "Come on in!", Speaker::TABLE },
/* 012 */	DialogJump { 0 },
/* 013 */	DialogJump { 21 },
/* 014 */	DialogChoice { "Kerry: I don't think so...", 19, nullptr },
/* 015 */	DialogLine { "That's quite a rude thing to say don't you think? I think that you should take a deep breath. Just to calm yourself down!", Speaker::TABLE },
/* 016 */	DialogLine { "I'm sorry", Speaker::KERRY },
/* 017 */	DialogLine { "You better be!", Speaker::TABLE },
/* 018 */	DialogJump { 21 },
/* 019 */	DialogChoice { "Kerry: Here's a cat!", 0, has_cat },
/* 020 */	DialogLine { "Thank you!", Speaker::TABLE },
/* 021 */	DialogJump { 0 },
};

