// This file is autogenerated do not edit please

#pragma once

#include "font_structures.h"

constexpr Font fonts[] {
	{ImageFile::SMALL_FONT_IMAGE, 16, 16, 32},
	{ImageFile::MEDIUM_FONT_IMAGE, 24, 24, 48},
	{ImageFile::LARGE_FONT_IMAGE, 48, 48, 96},
};

constexpr int NUMBER_OF_FONTS = 3;

