// This is an autogenerated file do NOT edit.

#pragma once

#include "shader_structures.h"
#include "SDL3/SDL_gpu.h"

static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"

constexpr u8 text_dxil[] {
	#embed "..\assets\shaders\dxil\text.frag.hlsl.dxil"
};

constexpr u8 text_msl[] {
	#embed "..\assets\shaders\msl\text.frag.hlsl.msl"
};

constexpr u8 text_spv[] {
	#embed "..\assets\shaders\spv\text.frag.hlsl.spv"
};

#pragma clang diagnostic pop

enum class Shader {
	TEXT,
};

constexpr ShaderData shader_data[] {
	{{text_spv, sizeof(text_spv)}, {text_msl, sizeof(text_msl)}, {text_dxil, sizeof(text_dxil)}},
};

constexpr u8 number_of_shaders = 1;
extern SDL_GPUShader* loaded_shaders[number_of_shaders];

void create_dxil_shaders(SDL_GPUDevice* device);
void create_msl_shaders(SDL_GPUDevice* device);
void create_spv_shaders(SDL_GPUDevice* device);
