// This file is autogenerated! Do not edit!

#include "shader_data.h"

SDL_GPUShader* loaded_shaders[number_of_shaders]{};

void create_dxil_shaders(SDL_GPUDevice* device) {
	{
	u8 index = static_cast<u8>(Shader::TEXT);
	SDL_GPUShaderCreateInfo info {shader_data[index].dxil.size, shader_data[index].dxil.data, "main", SDL_GPU_SHADERFORMAT_DXIL, SDL_GPU_SHADERSTAGE_FRAGMENT, 0, 0, 0, 0};
	loaded_shaders[index] = SDL_CreateGPUShader(device, &info);
	}
};

void create_msl_shaders(SDL_GPUDevice* device) {
	{
	u8 index = static_cast<u8>(Shader::TEXT);
	SDL_GPUShaderCreateInfo info {shader_data[index].msl.size, shader_data[index].msl.data, "main", SDL_GPU_SHADERFORMAT_MSL, SDL_GPU_SHADERSTAGE_FRAGMENT, 0, 0, 0, 0};
	loaded_shaders[index] = SDL_CreateGPUShader(device, &info);
	}
};

void create_spv_shaders(SDL_GPUDevice* device) {
	{
	u8 index = static_cast<u8>(Shader::TEXT);
	SDL_GPUShaderCreateInfo info {shader_data[index].spv.size, shader_data[index].spv.data, "main", SDL_GPU_SHADERFORMAT_SPIRV, SDL_GPU_SHADERSTAGE_FRAGMENT, 0, 0, 0, 0};
	loaded_shaders[index] = SDL_CreateGPUShader(device, &info);
	}
};

