// This is an autogenerated file. Do not edit!

#pragma once

#include "dialog_structures.h"

enum class Speaker {
	KERRY,
	NARRATOR
};

void office_turn_on_lights();
void office_go_to_hallway();




constexpr Dialog ENRETTE_BODY[] {
/* 001 */	DialogLine { {"Mom?"}, Speaker::KERRY },
/* 002 */	DialogLine { {"She is dead."}, Speaker::NARRATOR },
/* 003 */	DialogJump { 0 },
};

constexpr Dialog LIGHT_SWITCH[] {
/* 001 */	DialogLine { {"You found the light switch."}, Speaker::NARRATOR },
/* 002 */	DialogChoice { {"I don't want to see."}, 5, nullptr },
/* 003 */	DialogJump { 0 },
/* 004 */	DialogJump { 7 },
/* 005 */	DialogChoice { {"Turn on the lights."}, 0, nullptr },
/* 006 */	DialogFunction { office_turn_on_lights },
/* 007 */	DialogJump { 0 },
};

constexpr Dialog DESK[] {
/* 001 */	DialogLine { {"The desk has a framed photograph of a smiling family. A mother, a father, a son, a daughter."}, Speaker::NARRATOR },
/* 002 */	DialogLine { {"Judging by the age of the daughter, this photo was taken decades ago."}, Speaker::NARRATOR },
/* 003 */	DialogLine { {"Presently, the daughter is dead on the carpet behind you."}, Speaker::NARRATOR },
/* 004 */	DialogJump { 0 },
};

constexpr Dialog CHARGING_STATION[] {
/* 001 */	DialogLine { {"This is where you sleep. You were sleeping when Enrette died. Why didn't she wake you?"}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog CALENDAR[] {
/* 001 */	DialogLine { {"The calendar says that it's July 15th 1835. You have been asleep for 3 days."}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog BOOKS[] {
/* 001 */	DialogLine { {"These books are unrealistically large."}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog DOOR[] {
/* 001 */	DialogLine { {"You hear danger ahead."}, Speaker::NARRATOR },
/* 002 */	DialogChoice { {"Open the door"}, 6, nullptr },
/* 003 */	DialogFunction { office_go_to_hallway },
/* 004 */	DialogJump { 0 },
/* 005 */	DialogJump { 8 },
/* 006 */	DialogChoice { {"Nevermind"}, 0, nullptr },
/* 007 */	DialogJump { 0 },
/* 008 */	DialogJump { 0 },
};

