// This is an autogenerated file. Do not edit!

#pragma once

#include "dialog_structures.h"

enum class Speaker {
	KERRY,
	NARRATOR
};

void hallway_outside_office();




constexpr Dialog ENRETTE_BODY[] {
/* 001 */	DialogLine { {"Mom?"}, Speaker::KERRY },
/* 002 */	DialogLine { {"She is dead."}, Speaker::NARRATOR },
/* 003 */	DialogJump { 0 },
};

constexpr Dialog DESK[] {
/* 001 */	DialogLine { {"The desk has a framed photograph of a smiling family. A mother, a father, a son, a daughter."}, Speaker::NARRATOR },
/* 002 */	DialogLine { {"Judging by the age of the daughter, this photo was taken decades ago."}, Speaker::NARRATOR },
/* 003 */	DialogLine { {"In present day, the daughter lies lifeless in front of you."}, Speaker::NARRATOR },
/* 004 */	DialogJump { 0 },
};

constexpr Dialog CHARGING_STATION[] {
/* 001 */	DialogLine { {"This is where you sleep. You were sleeping when Enrette died. Why didn't she wake you?"}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog CALENDAR[] {
/* 001 */	DialogLine { {"The calendar says that it's July 15th 1835. You have been asleep for 3 days."}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog BOOKS[] {
/* 001 */	DialogLine { {"These books are unrealistically large."}, Speaker::NARRATOR },
/* 002 */	DialogJump { 0 },
};

constexpr Dialog DOOR[] {
/* 001 */	DialogLine { {"You hear danger ahead."}, Speaker::NARRATOR },
/* 002 */	DialogChoice { {"Open the door"}, 6, nullptr },
/* 003 */	DialogFunction { hallway_outside_office },
/* 004 */	DialogJump { 0 },
/* 005 */	DialogJump { 8 },
/* 006 */	DialogChoice { {"Nevermind"}, 0, nullptr },
/* 007 */	DialogJump { 0 },
/* 008 */	DialogJump { 0 },
};

