// This is an autogenerated file. Do not edit!

#pragma once

#include "image_structures.h"

static_assert(true); // There's a clang bug that gives a warning unless this fucking thing is here
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"
#ifdef FILE_EMBED

constexpr char arrow[] {
	#embed "..\assets\art\arrow.png"
};

constexpr char cancelarea[] {
	#embed "..\assets\art\CancelArea.png"
};

constexpr char card[] {
	#embed "..\assets\art\card.png"
};

constexpr char enretteoffice[] {
	#embed "..\assets\art\EnretteOffice.png"
};

constexpr char fireball[] {
	#embed "..\assets\art\fireball.png"
};

constexpr char gamebar[] {
	#embed "..\assets\art\GameBar.png"
};

constexpr char grakeny[] {
	#embed "..\assets\art\Grakeny.png"
};

constexpr char healthbar[] {
	#embed "..\assets\art\healthbar.png"
};

constexpr char kerry[] {
	#embed "..\assets\art\kerry.png"
};

constexpr char queue[] {
	#embed "..\assets\art\Queue.png"
};

constexpr char reception[] {
	#embed "..\assets\art\Reception.png"
};

constexpr char saturn[] {
	#embed "..\assets\art\saturn.png"
};

constexpr char table[] {
	#embed "..\assets\art\table.png"
};

constexpr char test_background[] {
	#embed "..\assets\art\test_background.png"
};

constexpr char test_button[] {
	#embed "..\assets\art\test_button.png"
};

constexpr char text_background[] {
	#embed "..\assets\art\text_background.png"
};

constexpr char extra_small_font[] {
	#embed "..\assets\font\extra_small_font.png"
};

constexpr char large_font[] {
	#embed "..\assets\font\large_font.png"
};

constexpr char medium_font[] {
	#embed "..\assets\font\medium_font.png"
};

constexpr char medium_large_font[] {
	#embed "..\assets\font\medium_large_font.png"
};

constexpr char small_font[] {
	#embed "..\assets\font\small_font.png"
};

constexpr char small_medium_font[] {
	#embed "..\assets\font\small_medium_font.png"
};

constexpr char very_large_font[] {
	#embed "..\assets\font\very_large_font.png"
};

#pragma clang diagnostic pop
#endif
#ifndef FILE_EMBED
constexpr char arrow[] {};

constexpr char cancelarea[] {};

constexpr char card[] {};

constexpr char enretteoffice[] {};

constexpr char fireball[] {};

constexpr char gamebar[] {};

constexpr char grakeny[] {};

constexpr char healthbar[] {};

constexpr char kerry[] {};

constexpr char queue[] {};

constexpr char reception[] {};

constexpr char saturn[] {};

constexpr char table[] {};

constexpr char test_background[] {};

constexpr char test_button[] {};

constexpr char text_background[] {};

constexpr char extra_small_font[] {};

constexpr char large_font[] {};

constexpr char medium_font[] {};

constexpr char medium_large_font[] {};

constexpr char small_font[] {};

constexpr char small_medium_font[] {};

constexpr char very_large_font[] {};

#endif

constexpr const char* image_file_data[] {
	arrow,
	cancelarea,
	card,
	enretteoffice,
	fireball,
	gamebar,
	grakeny,
	healthbar,
	kerry,
	queue,
	reception,
	saturn,
	table,
	test_background,
	test_button,
	text_background,
	extra_small_font,
	large_font,
	medium_font,
	medium_large_font,
	small_font,
	small_medium_font,
	very_large_font,
};

constexpr int image_file_sizes[] {
	sizeof(arrow),
	sizeof(cancelarea),
	sizeof(card),
	sizeof(enretteoffice),
	sizeof(fireball),
	sizeof(gamebar),
	sizeof(grakeny),
	sizeof(healthbar),
	sizeof(kerry),
	sizeof(queue),
	sizeof(reception),
	sizeof(saturn),
	sizeof(table),
	sizeof(test_background),
	sizeof(test_button),
	sizeof(text_background),
	sizeof(extra_small_font),
	sizeof(large_font),
	sizeof(medium_font),
	sizeof(medium_large_font),
	sizeof(small_font),
	sizeof(small_medium_font),
	sizeof(very_large_font),
};

enum class ImageFile {
	ARROW_IMAGE,
	CANCELAREA_IMAGE,
	CARD_IMAGE,
	ENRETTEOFFICE_IMAGE,
	FIREBALL_IMAGE,
	GAMEBAR_IMAGE,
	GRAKENY_IMAGE,
	HEALTHBAR_IMAGE,
	KERRY_IMAGE,
	QUEUE_IMAGE,
	RECEPTION_IMAGE,
	SATURN_IMAGE,
	TABLE_IMAGE,
	TEST_BACKGROUND_IMAGE,
	TEST_BUTTON_IMAGE,
	TEXT_BACKGROUND_IMAGE,
	EXTRA_SMALL_FONT_IMAGE,
	LARGE_FONT_IMAGE,
	MEDIUM_FONT_IMAGE,
	MEDIUM_LARGE_FONT_IMAGE,
	SMALL_FONT_IMAGE,
	SMALL_MEDIUM_FONT_IMAGE,
	VERY_LARGE_FONT_IMAGE
};

constexpr ImageDimensions image_dimensions[] {
	{100, 100},
	{320, 38},
	{300, 400},
	{1920, 1080},
	{272, 192},
	{300, 100},
	{200, 300},
	{175, 21},
	{200, 300},
	{915, 81},
	{1920, 1080},
	{272, 192},
	{300, 200},
	{2339, 1654},
	{400, 200},
	{200, 100},
	{760, 12},
	{4560, 72},
	{2280, 36},
	{3420, 54},
	{1520, 24},
	{1900, 30},
	{6840, 108}
};

enum class Sprite {
	ARROW_DOT_1,
	ARROW_DOT_2,
	ARROW_DOT_3,
	ARROW_DOT_4,
	ARROW_ARROW_1,
	ARROW_ARROW_2,
	ARROW_ARROW_3,
	ARROW_ARROW_4,
	CANCELAREA_1,
	CARD_PSYCHIC_1,
	CARD_PSYCHIC_2,
	CARD_PSYCHIC_3,
	CARD_PSYCHIC_4,
	CARD_PSYCHIC_5,
	CARD_PSYCHIC_6,
	CARD_PSYCHIC_7,
	CARD_PSYCHIC_8,
	CARD_PSYCHIC_9,
	CARD_PSYCHIC_10,
	CARD_PSYCHIC_LVL_1,
	CARD_MAGIC_1,
	CARD_MAGIC_2,
	CARD_MAGIC_3,
	CARD_MAGIC_4,
	CARD_MAGIC_5,
	CARD_MAGIC_6,
	CARD_MAGIC_7,
	CARD_MAGIC_8,
	CARD_MAGIC_9,
	CARD_MAGIC_10,
	CARD_MAGIC_LVL_1,
	CARD_GROOVE_1,
	CARD_GROOVE_2,
	CARD_GROOVE_3,
	CARD_GROOVE_4,
	CARD_GROOVE_5,
	CARD_GROOVE_6,
	CARD_GROOVE_7,
	CARD_GROOVE_8,
	CARD_GROOVE_9,
	CARD_GROOVE_10,
	CARD_GROOVE_LVL_1,
	CARD_PSYCHIC_FX_1,
	CARD_PSYCHIC_FX_2,
	CARD_PSYCHIC_FX_3,
	CARD_MAGIC_FX_1,
	CARD_MAGIC_FX_2,
	CARD_MAGIC_FX_3,
	CARD_GROOVE_FX_1,
	CARD_GROOVE_FX_2,
	CARD_GROOVE_FX_3,
	ENRETTEOFFICE_BG_1,
	ENRETTEOFFICE_SHELF_1,
	ENRETTEOFFICE_DRAWER_1,
	ENRETTEOFFICE_TABLE_1,
	ENRETTEOFFICE_CHAIR_1,
	ENRETTEOFFICE_COUCH_1,
	ENRETTEOFFICE_VENT_1,
	ENRETTEOFFICE_VENT_2,
	ENRETTEOFFICE_VENT_3,
	ENRETTEOFFICE_GARBAGE_1,
	ENRETTEOFFICE_BOOKS_1,
	FIREBALL,
	GAMEBAR_START_1,
	GAMEBAR_START_2,
	GAMEBAR_START_3,
	GAMEBAR_END_1,
	GAMEBAR_END_2,
	GAMEBAR_END_3,
	GAMEBAR_POISON_START_1,
	GAMEBAR_BLEED_START_1,
	GAMEBAR_BAR_EFFECT_1,
	GAMEBAR_BAR_EFFECT_2,
	GAMEBAR_BAR_EFFECT_3,
	GAMEBAR_BAR_EFFECT_4,
	GAMEBAR_TICK_EFFECT_1,
	GAMEBAR_TICK_EFFECT_2,
	GAMEBAR_TICK_EFFECT_3,
	GAMEBAR_TICK_EFFECT_4,
	GRAKENY_1,
	GRAKENY_2,
	GRAKENY_3,
	HEALTHBAR_OUTLINE_1,
	HEALTHBAR_DYNAMIC_1,
	HEALTHBAR_GOOD_1,
	HEALTHBAR_EVIL_1,
	HEALTHBAR_NEUTRAL_1,
	HEALTHBAR_DIVIDER_1,
	KERRY_DOWN_CAPE_1,
	KERRY_DOWN_CAPE_2,
	KERRY_DOWN_CAPE_3,
	KERRY_DOWN_CAPE_4,
	KERRY_DOWN_CAPE_5,
	KERRY_DOWN_CAPE_6,
	KERRY_DOWN_RIGHT_LEG_1,
	KERRY_DOWN_RIGHT_LEG_2,
	KERRY_DOWN_RIGHT_LEG_3,
	KERRY_DOWN_RIGHT_LEG_4,
	KERRY_DOWN_LEFT_LEG_1,
	KERRY_DOWN_LEFT_LEG_2,
	KERRY_DOWN_LEFT_LEG_3,
	KERRY_DOWN_LEFT_LEG_4,
	KERRY_DOWN_FLOWER_1,
	KERRY_DOWN_FLOWER_2,
	KERRY_DOWN_FLOWER_3,
	KERRY_DOWN_FLOWER_4,
	KERRY_DOWN_FLOWER_5,
	KERRY_DOWN_FLOWER_6,
	KERRY_DOWN_BODY_1,
	KERRY_DOWN_BODY_2,
	KERRY_DOWN_BODY_3,
	KERRY_DOWN_BODY_4,
	KERRY_RIGHT_FLOWER_1,
	KERRY_RIGHT_FLOWER_2,
	KERRY_RIGHT_FLOWER_3,
	KERRY_RIGHT_FLOWER_4,
	KERRY_RIGHT_FLOWER_5,
	KERRY_RIGHT_FLOWER_6,
	KERRY_RIGHT_LEFT_LEG_1,
	KERRY_RIGHT_LEFT_LEG_2,
	KERRY_RIGHT_LEFT_LEG_3,
	KERRY_RIGHT_LEFT_LEG_4,
	KERRY_RIGHT_RIGHT_LEG_1,
	KERRY_RIGHT_RIGHT_LEG_2,
	KERRY_RIGHT_RIGHT_LEG_3,
	KERRY_RIGHT_RIGHT_LEG_4,
	KERRY_RIGHT_BODY_1,
	KERRY_RIGHT_BODY_2,
	KERRY_RIGHT_BODY_3,
	KERRY_RIGHT_BODY_4,
	KERRY_RIGHT_CAPE_1,
	KERRY_RIGHT_CAPE_2,
	KERRY_RIGHT_CAPE_3,
	KERRY_RIGHT_CAPE_4,
	KERRY_RIGHT_CAPE_5,
	KERRY_RIGHT_CAPE_6,
	KERRY_LEFT_FLOWER_1,
	KERRY_LEFT_FLOWER_2,
	KERRY_LEFT_FLOWER_3,
	KERRY_LEFT_FLOWER_4,
	KERRY_LEFT_FLOWER_5,
	KERRY_LEFT_FLOWER_6,
	KERRY_LEFT_RIGHT_LEG_1,
	KERRY_LEFT_RIGHT_LEG_2,
	KERRY_LEFT_RIGHT_LEG_3,
	KERRY_LEFT_RIGHT_LEG_4,
	KERRY_LEFT_LEFT_LEG_1,
	KERRY_LEFT_LEFT_LEG_2,
	KERRY_LEFT_LEFT_LEG_3,
	KERRY_LEFT_LEFT_LEG_4,
	KERRY_LEFT_BODY_1,
	KERRY_LEFT_BODY_2,
	KERRY_LEFT_BODY_3,
	KERRY_LEFT_BODY_4,
	KERRY_LEFT_CAPE_1,
	KERRY_LEFT_CAPE_2,
	KERRY_LEFT_CAPE_3,
	KERRY_LEFT_CAPE_4,
	KERRY_LEFT_CAPE_5,
	KERRY_LEFT_CAPE_6,
	KERRY_UP_FLOWER_1,
	KERRY_UP_FLOWER_2,
	KERRY_UP_FLOWER_3,
	KERRY_UP_FLOWER_4,
	KERRY_UP_FLOWER_5,
	KERRY_UP_FLOWER_6,
	KERRY_UP_BODY_1,
	KERRY_UP_BODY_2,
	KERRY_UP_BODY_3,
	KERRY_UP_LEFT_LEG_1,
	KERRY_UP_LEFT_LEG_2,
	KERRY_UP_LEFT_LEG_3,
	KERRY_UP_LEFT_LEG_4,
	KERRY_UP_RIGHT_LEG_1,
	KERRY_UP_RIGHT_LEG_2,
	KERRY_UP_RIGHT_LEG_3,
	KERRY_UP_RIGHT_LEG_4,
	KERRY_UP_CAPE_1,
	KERRY_UP_CAPE_2,
	KERRY_UP_CAPE_3,
	KERRY_UP_CAPE_4,
	KERRY_UP_CAPE_5,
	KERRY_UP_CAPE_6,
	QUEUE_4_1,
	QUEUE_4_2,
	QUEUE_3_1,
	QUEUE_3_2,
	QUEUE_2_1,
	QUEUE_2_2,
	QUEUE_1_1,
	QUEUE_1_2,
	QUEUE_STAR_1,
	QUEUE_STAR_2,
	QUEUE_STAR_3,
	QUEUE_STAR_4,
	RECEPTION_BACKGROUND_1,
	RECEPTION_WALL_1,
	RECEPTION_SOFA_1,
	RECEPTION_SOFA2_1,
	RECEPTION_TABLE_1,
	RECEPTION_DESK_1,
	SATURN,
	TABLE,
	TEST_BACKGROUND,
	TEST_BUTTON,
	TEXT_BACKGROUND_1,
	EXTRA_SMALL_FONT,
	LARGE_FONT,
	MEDIUM_FONT,
	MEDIUM_LARGE_FONT,
	SMALL_FONT,
	SMALL_MEDIUM_FONT,
	VERY_LARGE_FONT,
	NONE
};

constexpr SpriteAtlasTransform sprite_atlas_transform[] {
	{233, 54, 17, 16, 42, 40, 59, 56},
	{194, 54, 18, 19, 41, 37, 59, 56},
	{214, 54, 17, 18, 40, 39, 57, 57},
	{173, 54, 19, 19, 38, 39, 57, 58},
	{172, 0, 83, 52, 8, 22, 91, 74},
	{87, 55, 84, 52, 8, 21, 92, 73},
	{87, 0, 83, 53, 8, 20, 91, 73},
	{0, 0, 85, 57, 7, 18, 92, 75},
	{0, 0, 319, 37, 1, 1, 320, 38},
	{595, 800, 285, 386, 6, 9, 291, 395},
	{716, 1855, 133, 140, 167, 208, 300, 348},
	{1102, 1830, 252, 229, 48, 116, 300, 345},
	{1102, 1564, 270, 264, 30, 94, 300, 358},
	{1443, 1195, 277, 325, 23, 75, 300, 400},
	{861, 1189, 279, 348, 13, 13, 292, 361},
	{1443, 1522, 261, 343, 37, 40, 298, 383},
	{1169, 804, 291, 370, 0, 11, 291, 381},
	{1194, 402, 288, 400, 12, 0, 300, 400},
	{1499, 0, 294, 400, 3, 0, 297, 400},
	{1722, 1268, 64, 68, 228, 9, 292, 77},
	{290, 802, 285, 386, 6, 9, 291, 395},
	{1706, 1522, 86, 121, 196, 200, 282, 321},
	{1356, 1867, 170, 255, 96, 115, 266, 370},
	{0, 1553, 223, 316, 55, 39, 278, 355},
	{0, 1193, 252, 358, 34, 32, 286, 390},
	{861, 1539, 239, 373, 54, 14, 293, 387},
	{290, 1190, 253, 360, 32, 12, 285, 372},
	{1169, 1176, 272, 386, 14, 8, 286, 394},
	{0, 798, 288, 393, 12, 7, 300, 400},
	{901, 402, 291, 400, 9, 0, 300, 400},
	{770, 1555, 79, 78, 221, 0, 300, 78},
	{882, 804, 285, 383, 6, 12, 291, 395},
	{307, 1883, 151, 88, 122, 194, 273, 282},
	{0, 1871, 153, 182, 126, 154, 279, 336},
	{155, 1883, 150, 171, 127, 169, 277, 340},
	{1528, 1867, 181, 211, 106, 144, 287, 355},
	{514, 1855, 200, 218, 89, 147, 289, 365},
	{514, 1555, 254, 298, 41, 87, 295, 385},
	{254, 1552, 258, 329, 30, 38, 288, 367},
	{577, 1188, 282, 365, 5, 5, 287, 370},
	{1484, 799, 286, 394, 10, 0, 296, 394},
	{1722, 1195, 65, 71, 229, 6, 294, 77},
	{1201, 0, 296, 400, 4, 0, 300, 400},
	{1484, 402, 291, 395, 6, 4, 297, 399},
	{903, 0, 296, 400, 4, 0, 300, 400},
	{302, 0, 300, 400, 0, 0, 300, 400},
	{0, 402, 298, 394, 2, 6, 300, 400},
	{0, 0, 300, 400, 0, 0, 300, 400},
	{604, 0, 297, 399, 1, 1, 298, 400},
	{604, 401, 295, 397, 2, 3, 297, 400},
	{300, 402, 293, 398, 4, 2, 297, 400},
	{0, 0, 1920, 1080, 0, 0, 1920, 1080},
	{3182, 367, 380, 323, 296, 15, 676, 338},
	{3182, 0, 359, 362, 1135, 0, 1494, 362},
	{1925, 0, 1252, 841, 85, 239, 1337, 1080},
	{3546, 0, 154, 252, 1388, 496, 1542, 748},
	{3182, 695, 439, 249, 677, 134, 1116, 383},
	{3705, 0, 127, 118, 978, 9, 1105, 127},
	{3705, 123, 127, 118, 978, 9, 1105, 127},
	{3705, 246, 127, 118, 978, 9, 1105, 127},
	{3567, 257, 97, 135, 1395, 880, 1492, 1015},
	{1925, 846, 1123, 179, 227, 885, 1350, 1064},
	{0, 0, 272, 192, 0, 0, 272, 192},
	{435, 171, 215, 45, 39, 23, 254, 68},
	{0, 241, 214, 45, 40, 24, 254, 69},
	{0, 102, 214, 48, 40, 22, 254, 70},
	{216, 147, 217, 45, 39, 23, 256, 68},
	{0, 194, 215, 45, 40, 24, 255, 69},
	{262, 97, 215, 48, 40, 22, 255, 70},
	{217, 194, 215, 45, 39, 23, 254, 68},
	{434, 218, 215, 45, 39, 23, 254, 68},
	{513, 88, 244, 81, 28, 8, 272, 89},
	{513, 0, 244, 86, 28, 4, 272, 90},
	{262, 0, 249, 95, 25, 0, 274, 95},
	{0, 0, 260, 100, 19, 0, 279, 100},
	{759, 95, 21, 54, 28, 18, 49, 72},
	{759, 0, 17, 93, 31, 2, 48, 95},
	{679, 171, 25, 97, 30, 1, 55, 98},
	{652, 171, 25, 100, 34, 0, 59, 100},
	{217, 0, 102, 124, 48, 85, 150, 209},
	{109, 0, 106, 124, 46, 84, 152, 208},
	{0, 0, 107, 124, 44, 85, 151, 209},
	{0, 0, 173, 19, 1, 1, 174, 20},
	{178, 0, 169, 15, 3, 3, 172, 18},
	{178, 20, 169, 15, 3, 3, 172, 18},
	{0, 24, 169, 15, 3, 3, 172, 18},
	{174, 42, 169, 15, 3, 3, 172, 18},
	{352, 0, 6, 18, 1, 2, 7, 20},
	{410, 495, 93, 56, 55, 211, 148, 267},
	{181, 496, 98, 52, 57, 214, 155, 266},
	{0, 553, 99, 48, 59, 219, 158, 267},
	{301, 492, 104, 53, 62, 214, 166, 267},
	{284, 550, 106, 46, 66, 220, 172, 266},
	{0, 504, 117, 44, 70, 219, 187, 263},
	{493, 626, 25, 42, 111, 231, 136, 273},
	{523, 626, 25, 38, 111, 233, 136, 271},
	{572, 262, 23, 23, 120, 248, 143, 271},
	{162, 644, 29, 28, 123, 244, 152, 272},
	{414, 664, 19, 32, 67, 244, 86, 276},
	{572, 219, 23, 38, 66, 239, 89, 277},
	{164, 553, 75, 33, 62, 243, 137, 276},
	{125, 637, 32, 27, 57, 247, 89, 274},
	{462, 556, 35, 50, 79, 82, 114, 132},
	{104, 576, 30, 49, 86, 85, 116, 134},
	{71, 368, 28, 53, 91, 84, 119, 137},
	{348, 601, 29, 43, 95, 90, 124, 133},
	{462, 611, 26, 43, 102, 91, 128, 134},
	{382, 626, 27, 39, 107, 96, 134, 135},
	{0, 0, 119, 142, 40, 118, 159, 260},
	{370, 0, 116, 142, 43, 117, 159, 259},
	{124, 0, 118, 142, 43, 118, 161, 260},
	{247, 0, 118, 140, 44, 119, 162, 259},
	{470, 147, 16, 55, 94, 78, 110, 133},
	{347, 649, 16, 48, 97, 81, 113, 129},
	{470, 207, 15, 53, 97, 80, 112, 133},
	{223, 147, 19, 51, 100, 84, 119, 135},
	{575, 165, 20, 49, 102, 84, 122, 133},
	{314, 601, 29, 43, 101, 91, 130, 134},
	{341, 349, 12, 28, 94, 246, 106, 274},
	{341, 382, 12, 25, 94, 250, 106, 275},
	{241, 671, 18, 24, 95, 249, 113, 273},
	{31, 655, 34, 22, 93, 248, 127, 270},
	{482, 673, 15, 28, 97, 249, 112, 277},
	{341, 288, 14, 27, 98, 250, 112, 277},
	{116, 669, 22, 26, 93, 249, 115, 275},
	{314, 649, 28, 28, 97, 246, 125, 274},
	{491, 0, 76, 141, 63, 118, 139, 259},
	{491, 146, 75, 141, 63, 121, 138, 262},
	{0, 147, 105, 140, 65, 122, 170, 262},
	{189, 288, 72, 136, 66, 122, 138, 258},
	{558, 359, 37, 70, 45, 198, 82, 268},
	{71, 292, 34, 71, 51, 196, 85, 267},
	{508, 555, 36, 66, 56, 199, 92, 265},
	{244, 553, 31, 66, 61, 199, 92, 265},
	{395, 556, 30, 65, 59, 200, 89, 265},
	{430, 556, 27, 69, 66, 196, 93, 265},
	{572, 51, 18, 56, 87, 79, 105, 135},
	{223, 203, 19, 48, 94, 83, 113, 131},
	{574, 112, 21, 48, 95, 82, 116, 130},
	{572, 0, 23, 46, 95, 84, 118, 130},
	{242, 624, 26, 42, 98, 89, 124, 131},
	{62, 606, 26, 43, 101, 88, 127, 131},
	{523, 669, 18, 30, 92, 241, 110, 271},
	{393, 670, 15, 32, 95, 239, 110, 271},
	{553, 657, 24, 28, 88, 242, 112, 270},
	{414, 630, 30, 29, 81, 244, 111, 273},
	{341, 320, 14, 24, 89, 250, 103, 274},
	{223, 256, 16, 27, 89, 248, 105, 275},
	{368, 670, 20, 26, 84, 248, 104, 274},
	{273, 652, 29, 26, 74, 247, 103, 273},
	{360, 287, 72, 140, 66, 119, 138, 259},
	{110, 285, 74, 139, 65, 121, 139, 260},
	{266, 288, 70, 137, 68, 121, 138, 258},
	{0, 292, 66, 134, 69, 121, 135, 255},
	{549, 555, 31, 66, 121, 201, 152, 267},
	{122, 504, 37, 67, 123, 202, 160, 269},
	{552, 292, 43, 62, 124, 205, 167, 267},
	{532, 435, 53, 58, 125, 207, 178, 265},
	{508, 498, 58, 52, 124, 209, 182, 261},
	{0, 431, 60, 53, 126, 209, 186, 262},
	{280, 601, 29, 46, 84, 89, 113, 135},
	{211, 591, 26, 47, 92, 87, 118, 134},
	{178, 591, 28, 48, 97, 86, 125, 134},
	{31, 606, 26, 44, 99, 91, 125, 135},
	{0, 606, 26, 46, 103, 94, 129, 140},
	{139, 591, 34, 41, 104, 99, 138, 140},
	{247, 145, 108, 138, 46, 119, 154, 257},
	{360, 147, 105, 135, 48, 121, 153, 256},
	{110, 147, 108, 133, 46, 121, 154, 254},
	{0, 657, 22, 32, 68, 245, 90, 277},
	{93, 669, 18, 33, 71, 243, 89, 276},
	{211, 643, 25, 33, 64, 244, 89, 277},
	{449, 659, 28, 23, 58, 243, 86, 266},
	{572, 498, 23, 34, 112, 240, 135, 274},
	{70, 654, 18, 34, 114, 238, 132, 272},
	{93, 630, 27, 34, 113, 237, 140, 271},
	{553, 626, 36, 26, 111, 238, 147, 264},
	{71, 429, 105, 70, 49, 197, 154, 267},
	{437, 292, 107, 69, 54, 198, 161, 267},
	{437, 366, 115, 64, 56, 201, 171, 265},
	{181, 430, 115, 61, 60, 200, 175, 261},
	{417, 435, 110, 55, 69, 205, 179, 260},
	{301, 432, 111, 55, 74, 204, 185, 259},
	{0, 0, 873, 58, 35, 17, 908, 75},
	{875, 0, 870, 57, 37, 18, 907, 75},
	{1747, 0, 657, 57, 34, 17, 691, 74},
	{875, 59, 654, 55, 37, 19, 691, 74},
	{1531, 59, 436, 52, 34, 20, 470, 72},
	{1969, 59, 434, 50, 37, 21, 471, 71},
	{0, 60, 230, 47, 34, 22, 264, 69},
	{232, 60, 221, 48, 37, 23, 258, 71},
	{2547, 0, 59, 65, 27, 16, 86, 81},
	{455, 60, 56, 62, 28, 15, 84, 77},
	{2480, 0, 65, 69, 24, 11, 89, 80},
	{2406, 0, 72, 72, 24, 8, 96, 80},
	{0, 0, 1920, 1080, 0, 0, 1920, 1080},
	{0, 1085, 1920, 306, 0, 0, 1920, 306},
	{3007, 288, 368, 271, 38, 146, 406, 417},
	{3007, 0, 515, 283, 868, 140, 1383, 423},
	{2454, 0, 548, 566, 844, 281, 1392, 847},
	{1925, 0, 524, 703, 1363, 104, 1887, 807},
	{0, 0, 272, 192, 0, 0, 272, 192},
	{0, 0, 300, 200, 56, 56, 257, 190},
	{0, 0, 2339, 1654, 0, 0, 2339, 1654},
	{0, 0, 400, 200, 0, 0, 400, 200},
	{0, 0, 196, 97, 2, 1, 198, 98},
	{0, 0, 760, 12, 11, 2, 760, 10},
	{0, 0, 4560, 72, 54, 10, 4540, 56},
	{0, 0, 2280, 36, 28, 5, 2272, 28},
	{0, 0, 3420, 54, 41, 8, 3406, 42},
	{0, 0, 1520, 24, 20, 4, 1516, 20},
	{0, 0, 1900, 30, 24, 4, 1894, 24},
	{0, 0, 6840, 108, 80, 16, 6809, 84}
};

constexpr ImageFile sprite_to_image_file[] {
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::ARROW_IMAGE,
	ImageFile::CANCELAREA_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::CARD_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::ENRETTEOFFICE_IMAGE,
	ImageFile::FIREBALL_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GAMEBAR_IMAGE,
	ImageFile::GRAKENY_IMAGE,
	ImageFile::GRAKENY_IMAGE,
	ImageFile::GRAKENY_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::HEALTHBAR_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::KERRY_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::QUEUE_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::RECEPTION_IMAGE,
	ImageFile::SATURN_IMAGE,
	ImageFile::TABLE_IMAGE,
	ImageFile::TEST_BACKGROUND_IMAGE,
	ImageFile::TEST_BUTTON_IMAGE,
	ImageFile::TEXT_BACKGROUND_IMAGE,
	ImageFile::EXTRA_SMALL_FONT_IMAGE,
	ImageFile::LARGE_FONT_IMAGE,
	ImageFile::MEDIUM_FONT_IMAGE,
	ImageFile::MEDIUM_LARGE_FONT_IMAGE,
	ImageFile::SMALL_FONT_IMAGE,
	ImageFile::SMALL_MEDIUM_FONT_IMAGE,
	ImageFile::VERY_LARGE_FONT_IMAGE
};

constexpr int NUMBER_OF_IMAGES = 23;

