// THIS IS AUTOGENERATED FILE NO DO NOT EDIT

#pragma once

#include "../basic/vector2.h"
#include "../basic/shapes.h"

namespace LD {
constexpr Vector2 ENRETTEOFFICE_ENEMY_POSITION = {971.0, -272.0};
constexpr Vector2 ENRETTEOFFICE_PLAYER_POSITION = {467.0, -383.0};
constexpr Box ENRETTEOFFICE_TABLE_BOX = {{1134.0, -366.0}, {1327.0, -690.0}};
constexpr Box ENRETTEOFFICE_COUCH_BOX = {{690.0, -266.0}, {1095.0, -370.0}};
constexpr Box ENRETTEOFFICE_SHELF_BOX = {{324.0, -233.0}, {674.0, -336.0}};
constexpr Box ENRETTEOFFICE_DRAWER_BOX = {{1174.0, -262.0}, {1471.0, -346.0}};
constexpr Box ENRETTEOFFICE_CHAIR_BOX = {{1389.0, -649.0}, {1514.0, -738.0}};
constexpr Box ENRETTEOFFICE_BOOKS_BOX = {{245.0, -971.0}, {1350.0, -1054.0}};
constexpr Box ENRETTEOFFICE_GARBAGE_BOX = {{1399.0, -959.0}, {1497.0, -1020.0}};
constexpr Box ENRETTEOFFICE_DOOR_BOX = {{220.25, -445.3125}, {337.0, -684.0}};
constexpr Box ENRETTEOFFICE_LIGHT_SWITCH = {{86.75, -564.8125}, {183.25, -870.0}};
constexpr Box ENRETTEOFFICE_CALENDAR = {{1602.375, -588.703125}, {1759.625, -923.296875}};
constexpr Box ENRETTEOFFICE_CHARGING = {{539.375, -335.7031225}, {670.0, -398.9999975}};
constexpr Vector2 ENRETTEOFFICE_ENTRANCE_POSITION = {403.0, -583.0};
constexpr Polygon ENRETTEOFFICE_BORDER = {{Vector2{88,-1072},Vector2{1669,-1072},Vector2{1475,-294},Vector2{324,-270},}};
constexpr Box KERRY_COLLISION = {{47.0, -251.0}, {151.0, -291.0}};
constexpr Box OFFICE_HALL_TO_RECEPTION = {{-11.5, -2422.0}, {75.0, -2998.0}};
constexpr Box OFFICE_HALL_TO_OFFICE = {{1106.75, -438.0}, {1193.25, -1014.0}};
constexpr Vector2 OFFICE_HALL_RECEPTION_ENTRANCE = {180.0, -2730.0};
constexpr Vector2 OFFICE_HALL_OFFICE_ENTRANCE = {953.0, -720.0};
constexpr Polygon OFFICE_HALL_BORDER = {{Vector2{-20,-2530},Vector2{722,-2506},Vector2{689,-414},Vector2{1211,-410},Vector2{1211,-2958},Vector2{-16,-2966},}};
constexpr Box RECEPTION_SOFA_1 = {{42.0, -294.0}, {388.0, -401.0}};
constexpr Box RECEPTION_SOFA_2 = {{895.0, -274.75}, {1383.0, -425.0}};
constexpr Box RECEPTION_TABLE = {{849.5, -704.0}, {1128.0, -850.0}};
constexpr Vector2 RECEPTION_HALLWAY_POSITION = {1747.0, -932.0};
constexpr Box RECEPTION_TO_HALLWAY = {{1809.0, -819.0}, {1930.0, -1084.0}};
constexpr Box RECEPTION_TO_ELEVATOR = {{432.75, -266.75}, {812.0, -371.0}};
constexpr Vector2 RECEPTION_ELEVATOR_ENTRANCE = {606.0, -448.0};
constexpr Polygon RECEPTION_DESK = {{Vector2{1399,-272},Vector2{1830,-224},Vector2{1888,-794},Vector2{1590,-808},Vector2{1366,-694},}};
constexpr Polygon RECEPTION_BORDER = {{Vector2{-7,-287},Vector2{1928,-287},Vector2{1928,-1069},Vector2{-7,-1069},}};
}
